import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [
    {
      url: "https://cdn.prod.website-files.com/67899ab4e6c7ecc71a7add09/67a535546209b8a41217a98a_alma%20favicon.png",
      rel: "icon",
    },
    {
      url: "https://cdn.prod.website-files.com/67899ab4e6c7ecc71a7add09/678fa55b86f976d7dd90a70e_Frame%20136572%201%20(1).svg",
      rel: "apple-touch-icon",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
